### ISSUE TITLE
[Bug] Wrong description on readme.

### ISSUE THREAD

**Issue by boybeak** [katorlys/prism-theme-github#1]
### Describe the bug

At the **Github Dark** part description, a wrong link is provided, it's the light theme link.

### Operating system and its version

none

### Programming language and its version

none

### Dependencies and their versions

none

### Steps to Reproduce

1. none

### Expected behavior

none

### Actual behavior

none

**Comment by katorly** [comment]
Thanks for the reminder!

**Comment by katorly** [comment]
Fixed in [1.0.2](https://github.com/katorlys/prism-theme-github/releases/tag/1.0.2)
